name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  http_parser: ^4.0.2
  geolocator: ^13.0.1
  record: ^6.1.2
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/client_meeting_icon.png

# App icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/client_meeting_icon.png"
  # If you later want adaptive icons:
  # adaptive_icon_background: "#020617"
  # adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
